language: haskell
ghc:
  - 8.4.4
  - 8.6.2
cabal: 2.4

install:
  - export PATH=$HOME/.cabal/bin:$PATH &&
    cabal new-update

script:
  - gzip -cd test.prof.gz |
      cabal new-run -v0 prof-flamegraph |
      sort > test.trace &&
    diff test.trace.golden test.trace

before_cache:
  - rm -rf $HOME/.cabal/logs

cache:
  apt: true
  directories:
  - "$HOME/.ghcup"
  - "$HOME/.cabal"

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: hackage
  username: fommil
  password:
    secure: JtvjAkHPBCRvty6VtLIkLHPqTO+VQr0iLgzrFn0f/RDvoWMvblVfihrFJoJnyeS567Dlsft4k8uQfsiy+XIhLOiXgV+LRBygfcXEUT0KaEQrhEwqrSVxPwrCnVCyRdNEsrBIiF1XG24nOYlHEsWtBIqW9g1wgMpt0FA2vVy4rGKXVA2qdS31vowRgbJyEQoeeDYRqI1hZ18AWJBH9M7Cy06Se4uH0ts9aZj5Pk2mGYVOZigH19uQTiNUK2TqPVGoo+B1lIkJnsBbTCcXFB/HFqPRRn6aunjM89MwWojSM4hx4E4+jTtyZQhjQ1R7RIvEKBjQg/a9mWhCOwIkfTSTCNmijDqeWSO+2R9cFx78/3WOAFcffbghYs3cNKJM61Hspvv/sJwuJ/0afgAbsDBDPmf1R+sOAz1BDwis2knZH6WTtQ5Wjoxt0eKrwvLH3fa90Oi0wY1VBuRX3EoETwUwW1XtHDzVn/Y2MmTy99T+Hhtdd82iVrIJ9N6IwAPq+K+z3qH3ErlSpbgfCve2SmWv6o98XqLYjLtM5xgFzrFx2zR/FpgNw7ulGdvzT9aDMq6XDVCPUdhLUJ9Gwo9MdDmsObIeNKURSRpgc5wXdYY5kuAyOUYK/1x6tdDR83nNUMyYpCwBfRkCte4M92yCXhQcfPPc7q6KeLJ/57GLErORwVI=
  on:
    tags: true
    repo: symbiont-io/prof-flamegraph
    condition: $TRAVIS_HASKELL_VERSION = 8.4.4
